/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Admin;

import database.DatabaseConnection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Disath Damsutha
 */
public class UserManagement extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(UserManagement.class.getName());
    private DefaultTableModel tableModel;

    /**
     * Creates new form UserManagement
     */
    public UserManagement() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        // Load users from database
        loadUsers();

        // Add Mouse Listener for Table (To fix row click)
        usertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usertableMouseClicked(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        MainPanel = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        lblusername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblpassword = new javax.swing.JLabel();
        txtUsername2 = new javax.swing.JTextField();
        lblrole = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        lblpassword1 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        Heder = new javax.swing.JPanel();
        lblheader = new javax.swing.JLabel();
        Rightside = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usertable = new javax.swing.JTable();
        lblsearch = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        lblsearch1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(1530, 955));

        MainPanel.setBackground(new java.awt.Color(243, 247, 244));

        SidePanel.setBackground(new java.awt.Color(73, 149, 51));

        lblusername.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        lblusername.setForeground(new java.awt.Color(5, 63, 22));
        lblusername.setText("Username :");

        lblpassword.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(5, 63, 22));
        lblpassword.setText("Password :");

        lblrole.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        lblrole.setForeground(new java.awt.Color(5, 63, 22));
        lblrole.setText("Role     :");

        cmbRole.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Cashier" }));

        btnadd.setBackground(new java.awt.Color(147, 202, 55));
        btnadd.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(147, 186, 40));
        btnupdate.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        btnupdate.setText("UpDate");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(255, 102, 102));
        btndelete.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(153, 153, 153));
        btnclear.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(153, 153, 153));
        btnback.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        lblpassword1.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        lblpassword1.setForeground(new java.awt.Color(5, 63, 22));
        lblpassword1.setText("Phone    :");

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
                SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SidePanelLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(SidePanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblpassword1)
                                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 147,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblrole)
                                        .addComponent(lblpassword)
                                        .addComponent(lblusername)
                                        .addComponent(txtUsername2)
                                        .addComponent(txtUsername)
                                        .addComponent(cmbRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(SidePanelLayout.createSequentialGroup()
                                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 147,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62,
                                                        Short.MAX_VALUE)
                                                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 147,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidePanelLayout
                                                .createSequentialGroup()
                                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 147,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 147,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtPhone))
                                .addContainerGap(46, Short.MAX_VALUE)));
        SidePanelLayout.setVerticalGroup(
                SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SidePanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblusername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblpassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblrole)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblpassword1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(
                                        SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(
                                        SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)));

        Heder.setBackground(new java.awt.Color(73, 128, 37));
        Heder.setPreferredSize(new java.awt.Dimension(1000, 60));

        lblheader.setFont(new java.awt.Font("Unispace", 1, 20)); // NOI18N
        lblheader.setForeground(new java.awt.Color(243, 247, 244));
        lblheader.setText("User Management");

        javax.swing.GroupLayout HederLayout = new javax.swing.GroupLayout(Heder);
        Heder.setLayout(HederLayout);
        HederLayout.setHorizontalGroup(
                HederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HederLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblheader)
                                .addGap(867, 867, 867)));
        HederLayout.setVerticalGroup(
                HederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HederLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblheader, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                .addContainerGap()));

        Rightside.setBackground(new java.awt.Color(243, 247, 244));

        usertable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        usertable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "ID", "Username", "Role", "Phone", "Created_at"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        usertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usertableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usertable);

        lblsearch.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        lblsearch.setForeground(new java.awt.Color(5, 63, 22));
        lblsearch.setText("Search By Name/ID :");

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        lblsearch1.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        lblsearch1.setForeground(new java.awt.Color(5, 63, 22));
        lblsearch1.setText("All Users :");

        javax.swing.GroupLayout RightsideLayout = new javax.swing.GroupLayout(Rightside);
        Rightside.setLayout(RightsideLayout);
        RightsideLayout.setHorizontalGroup(
                RightsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RightsideLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(RightsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(RightsideLayout.createSequentialGroup()
                                                .addComponent(lblsearch1)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightsideLayout
                                                .createSequentialGroup()
                                                .addGroup(RightsideLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jScrollPane1)
                                                        .addGroup(RightsideLayout.createSequentialGroup()
                                                                .addGroup(RightsideLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(lblsearch,
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtsearch,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                563,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 850, Short.MAX_VALUE)))
                                                .addGap(33, 33, 33)))));
        RightsideLayout.setVerticalGroup(
                RightsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RightsideLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblsearch)
                                .addGap(17, 17, 17)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblsearch1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(180, Short.MAX_VALUE)));

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(Rightside, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(Heder, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE));
        MainPanelLayout.setVerticalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(Heder, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Rightside, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SidePanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        setSize(new java.awt.Dimension(1936, 1089));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usertableMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_usertableMouseClicked
        // 1. Get the selected row index
        int selectedRow = usertable.getSelectedRow();

        // 2. Pull data from the table into the text fields
        String username = usertable.getValueAt(selectedRow, 1).toString();
        String role = usertable.getValueAt(selectedRow, 2).toString();

        Object phoneObj = usertable.getValueAt(selectedRow, 3);
        String phone = (phoneObj != null) ? phoneObj.toString() : "";

        txtUsername.setText(username);
        cmbRole.setSelectedItem(role);
        txtPhone.setText(phone);

        // 3. Simple try-catch to get the password from the database
        try {
            String id = usertable.getValueAt(selectedRow, 0).toString();
            Connection conn = DatabaseConnection.getConnection();
            Statement s = conn.createStatement();
            ResultSet rs = s.executeQuery("SELECT password FROM users WHERE user_id = '" + id + "'");

            if (rs.next()) {
                txtUsername2.setText(rs.getString("password"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }// GEN-LAST:event_usertableMouseClicked

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {
        searchUsers();
    }

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {
        // 1. Get text from the fields
        String username = txtUsername.getText();
        String password = txtUsername2.getText();
        String role = cmbRole.getSelectedItem().toString();
        String phone = txtPhone.getText();

        // 2. Simple check for empty fields
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all fields!");
            return;
        }

        // 3. Database Save Logic (Beginner style)
        try {
            Connection conn = DatabaseConnection.getConnection();
            String sql = "INSERT INTO users (username, password, full_name, user_role, phone) VALUES (?, ?, ?, ?, ?)";
            // Note: full_name and user_role are guesses based on schema, but user only
            // added phone column.
            // Actually, checking schema:
            // username, password, full_name, phone, role

            sql = "INSERT INTO users (username, password, full_name, role, phone) VALUES (?, ?, ?, ?, ?)";

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, password);
            pst.setString(3, username); // full_name = username
            pst.setString(4, role);
            pst.setString(5, phone);

            int rs = pst.executeUpdate();
            if (rs > 0) {
                JOptionPane.showMessageDialog(null, "Inserted Successfully!");
                loadUsers();
                clearFields();
            } else {
                System.out.println("Failed to Save");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = usertable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Select a user to update!");
            return;
        }

        String userId = usertable.getValueAt(selectedRow, 0).toString();
        String username = txtUsername.getText();
        String password = txtUsername2.getText();
        String role = cmbRole.getSelectedItem().toString();
        String phone = txtPhone.getText();

        try {
            Connection conn = DatabaseConnection.getConnection();
            String sql = "UPDATE users SET username=?, password=?, full_name=?, role=?, phone=? WHERE user_id=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, password);
            pst.setString(3, username); // full_name = username
            pst.setString(4, role);
            pst.setString(5, phone);
            pst.setString(6, userId);

            int rs = pst.executeUpdate();
            if (rs > 0) {
                JOptionPane.showMessageDialog(null, "Updated Successfully!");
                loadUsers();
                clearFields();
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {
        clearFields();
    }

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {
        // 1. Get the information from the table
        int selectedRow = usertable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a user to delete!");
            return;
        }

        String userId = usertable.getValueAt(selectedRow, 0).toString();
        String role = usertable.getValueAt(selectedRow, 2).toString();

        // 2. Prevent deleting Admin
        if (role.equalsIgnoreCase("Admin")) {
            JOptionPane.showMessageDialog(null, "Admin users cannot be deleted!");
            return;
        }

        // 3. Confirm and Delete
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Connection conn = DatabaseConnection.getConnection();
                PreparedStatement pst = conn.prepareStatement("DELETE FROM users WHERE user_id = ?");
                pst.setString(1, userId);

                int rs = pst.executeUpdate();
                if (rs > 0) {
                    JOptionPane.showMessageDialog(null, "Deleted Successfully!");
                    loadUsers();
                    clearFields();
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {
        new AdminDashboard().setVisible(true);
        this.dispose();
    }

    // Method to load data to the table
    private void loadUsers() {
        try {
            DefaultTableModel dt = (DefaultTableModel) usertable.getModel();
            dt.setRowCount(0); // Clear current table

            Connection conn = DatabaseConnection.getConnection();
            Statement s = conn.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM users");

            while (rs.next()) {
                Object[] row = {
                        rs.getString("user_id"),
                        rs.getString("username"),
                        rs.getString("role"),
                        rs.getString("phone"),
                        rs.getString("created_at")
                };
                dt.addRow(row);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    // Method to clear the input fields
    private void clearFields() {
        txtUsername.setText("");
        txtUsername2.setText("");
        cmbRole.setSelectedIndex(0);
        txtsearch.setText("");
        txtPhone.setText("");
    }

    // Logic for Search (Simplified)
    private void searchUsers() {
        String search = txtsearch.getText();
        try {
            DefaultTableModel dt = (DefaultTableModel) usertable.getModel();
            dt.setRowCount(0);

            Connection conn = DatabaseConnection.getConnection();
            Statement s = conn.createStatement();
            ResultSet rs = s.executeQuery(
                    "SELECT * FROM users WHERE username LIKE '%" + search + "%' OR user_id LIKE '%" + search + "%' ");

            while (rs.next()) {
                Object[] row = {
                        rs.getString("user_id"),
                        rs.getString("username"),
                        rs.getString("role"),
                        rs.getString("phone"),
                        rs.getString("created_at")
                };
                dt.addRow(row);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Heder;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Rightside;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblheader;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblpassword1;
    private javax.swing.JLabel lblrole;
    private javax.swing.JLabel lblsearch;
    private javax.swing.JLabel lblsearch1;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsername2;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTable usertable;
    // End of variables declaration//GEN-END:variables
}
